chore: set std explicitly
It compiled without this for me, but we should be explicit:

> After a long period of stability, three new header files (iso646.h,
> wchar.h, and wctype.h) were added with Normative Addendum 1 (NA1), an
> addition to the C Standard ratified in 1995. Six more header files
> (complex.h, fenv.h, inttypes.h, stdbool.h, stdint.h, and tgmath.h)
> were added with C99, a revision to the C Standard published in
> 1999, and five more files (stdalign.h, stdatomic.h, stdnoreturn.h,
> threads.h, and uchar.h) with C11 in 2011. In total, there are now 29
> header files

https://en.wikipedia.org/wiki/C_standard_library

Note that this produced new compiler errors because I was using
`typeof`, a non-standard extension:

    watchman.c:418:25: error: call to undeclared function 'typeof'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        if (r->ptr + sizeof(typeof(WATCHMAN_DOUBLE_MARKER)) + sizeof(double) >
                            ^
    1 error generated.

The type here is just `int`, so maybe I should just hard-code it...
anyway, for now keeping it in in the form of `__typeof__`, which works
in both Clang and GCC.