fix: guard against error E315
Hopefully mitigates this kind of error on accepting a selection:

    Error detected while processing function commandt#private#AcceptSelection:
    line    1:
    RuntimeError: Vim:E315: ml_get: invalid lnum: 19

With this relevant stack trace excerpt:

    /Library/Ruby/Gems/2.3.0/gems/neovim-0.8.0/lib/neovim/window.rb:27:in `height='
    /Users/glh/.config/nvim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/match_window.rb:356:in `block in restore_window_views'
    /Users/glh/.config/nvim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/match_window.rb:353:in `each'
    /Users/glh/.config/nvim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/match_window.rb:353:in `restore_window_views'
    /Users/glh/.config/nvim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/match_window.rb:205:in `unload'
    /Users/glh/.config/nvim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/match_window.rb:201:in `leave'
    /Users/glh/.config/nvim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/controller.rb:155:in `hide'
    /Users/glh/.config/nvim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/controller.rb:237:in `accept_selection'
    (eval):3:in `accept_selection'
    eval:1:in `<main>'

Sadly only "hopefully", because I don't have a reliable repro.

Possibly related:

    https://github.com/wincent/command-t/issues/266#issuecomment-316833804