This patch fixed two 'compatibility' issues of command-t related to Ruby 1.8.5 on my CentOS 5.4 box.
Vim 7.4 issues some error messages on CentOS 5.4:

    1. NoMethodError: undefined method `each_char' for "":String

    2. NoMethodError: undefined method `[]' for nil:NilClas

It turns out that there is no String.chars method in Ruby version 1.8.5.

       $ ruby --version
       ruby 1.8.5 (2006-08-25) [x86_64-linux]

In lieu of 'chars' method used in 'ruby/command-t/match_window.rb', I
use 'each_char.to_a' method.

Somehow the range syntax doesn't work ('0'..'9') either, which caused
the second error message. I have hard coded 'numbers' and 'lowercase' in
'def register_for_key_presses' for better compatibility. This is a bit
of strange because I can use the same range syntax in Ruby interactive
shell. But I am not able to tell what caused the inconsistency concerned
with the range syntax due to my lack of Ruby knoweledge.